version: '3'

services:
    backend:
        build:
          context: ./
        container_name: backend
        hostname: backend
        ports:
            - "8080:8080"

    frontend:
        image: nginx
        ports:
          - "80:80"
        volumes:
          - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
          # - ./nginx/ssl:/etc/nginx/ssl:ro
          # - ./nginx/index.html:/app/html:ro

# configs:
#   nginx_conf:
#     file: ./frontend/nginx.conf
